language: python
os: linux
dist: focal
jobs:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.9"
      env: TOXENV=py39
    - python: "3.9"
      env: TOXENV=flake8
    - python: "3.9"
      env: TOXENV=pylint
    - python: "3.9"
      env: TOXENV=typing
    - python: "3.9"
      env: TOXENV=pydocstyle
install: pip install -U tox
script: tox
services:
  - docker
