[tox]
envlist = py310, py311, py312, py313, py314, ruff, pylint, codespell, mypy, deptry

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312, ruff, pylint, codespell, mypy, deptry
    3.13: py313
    3.14: py314

[testenv]
package = editable
commands = py.test --cov=didl_lite --cov-report=term --cov-report=xml:coverage-{env_name}.xml {posargs}
ignore_errors = True
deps = -r requirements/tox-testenv/requirements.txt

[testenv:ruff]
basepython = python3
ignore_errors = True
deps = -r requirements/tox-ruff/requirements.txt
commands =
    ruff check didl_lite tests
    ruff format --check didl_lite tests

[testenv:pylint]
basepython = python3
ignore_errors = True
deps = -r requirements/tox-pylint/requirements.txt
commands = pylint didl_lite tests

[testenv:codespell]
basepython = python3
ignore_errors = True
deps = -r requirements/tox-codespell/requirements.txt
commands = codespell didl_lite tests

[testenv:mypy]
basepython = python3
ignore_errors = True
deps = -r requirements/tox-mypy/requirements.txt
commands = mypy --ignore-missing-imports didl_lite tests

[testenv:deptry]
basepython = python3
ignore_errors = True
deps = -r requirements/tox-deptry/requirements.txt
commands = deptry .
